(() => {
  "use strict";
  const CLIENT_ID="338694338436-cec75dabc9qefhm4ad8q8fj1r1g2tcc0.apps.googleusercontent.com";
  const API_KEY="AIzaSyAwIYKOm2CmuTnDAxP8Blb95oKGRFVpy8g";
  const APP_ID="338694338436";
  const SCOPE="https://www.googleapis.com/auth/drive.file";
  const MARKER_KEY="babyRecordDatabase",MARKER_VALUE="v1";
  const RECORD_HEADERS=["id","kind","date","time","summary","details_json","created_by","created_at","updated_at"];
  const SLEEP_HEADERS=["id","start_time","end_time","duration_min","status","created_by","created_at","updated_at"];
  const kinds={feeding:{label:"喝奶",icon:"◒",tone:"peach"},pee:{label:"小便",icon:"◜",tone:"blue"},poop:{label:"大便",icon:"♨",tone:"gold"},sleep:{label:"睡眠",icon:"☾",tone:"lavender"},temperature:{label:"體溫",icon:"°",tone:"rose"},jaundice:{label:"黃疸",icon:"☼",tone:"yellow"},growth:{label:"成長",icon:"↗",tone:"mint"},food:{label:"副食品",icon:"⌇",tone:"sage"}};
  const $=s=>document.querySelector(s);
  const state={token:null,tokenClient:null,user:null,database:null,records:[],activeStart:null,filter:"all",activeKind:null,editingId:null,values:{},busy:false};
  let toastTimer,sleepTimer;

  async function waitFor(check,timeout=12000){const start=Date.now();while(!check()){if(Date.now()-start>timeout)throw new Error("Google 登入元件載入逾時，請重新整理後再試");await new Promise(r=>setTimeout(r,100))}}
  async function prepareGoogle(){await waitFor(()=>window.google?.accounts?.oauth2);state.tokenClient=google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:async response=>{if(response.error)return showToast("Google 登入未完成");state.token=response.access_token;try{await afterGoogleLogin()}catch(error){showError(error)}}})}
  async function connectGoogle(){try{if(!state.tokenClient)await prepareGoogle();state.tokenClient.requestAccessToken({prompt:state.token?"":"consent"})}catch(error){showError(error)}}
  async function afterGoogleLogin(){setBusy(true);const about=await googleFetch("https://www.googleapis.com/drive/v3/about?fields=user");state.user=about.user;$("#accountLabel").textContent=`目前帳號：${state.user.emailAddress||state.user.displayName}`;await loadDatabaseChoices();const saved=localStorage.getItem(databaseStorageKey());if(saved){const db=state.databases.find(x=>x.id===saved)||{id:saved,name:"寶寶生理紀錄"};try{await chooseDatabase(db);return}catch{localStorage.removeItem(databaseStorageKey())}}showOnly("databaseSetup");setBusy(false)}
  function databaseStorageKey(){return`baby-record.database.${state.user?.emailAddress||"unknown"}`}
  async function googleFetch(url,options={}){if(!state.token)throw new Error("請先重新連接 Google");const headers={Accept:"application/json",Authorization:`Bearer ${state.token}`,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})};let response;try{response=await fetch(url,{...options,headers})}catch{throw new Error("目前沒有網路連線")}if(response.status===401){state.token=null;setConnection("expired");throw new Error("Google 連線已到期，請按「重新連接」")};const text=await response.text();const data=text?JSON.parse(text):{};if(!response.ok)throw new Error(data.error?.message||`Google API 發生錯誤（${response.status}）`);return data}
  async function loadDatabaseChoices(){const q=`mimeType='application/vnd.google-apps.spreadsheet' and trashed=false and appProperties has { key='${MARKER_KEY}' and value='${MARKER_VALUE}' }`;const url=`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name,modifiedTime)&orderBy=modifiedTime%20desc`;const data=await googleFetch(url);state.databases=data.files||[];renderDatabaseChoices()}
  function renderDatabaseChoices(){const root=$("#databaseList");root.replaceChildren();state.databases.forEach(db=>{const b=document.createElement("button");b.className="database-option";b.textContent=db.name;b.onclick=()=>chooseDatabase(db).catch(showError);root.append(b)});$("#existingSection").hidden=!state.databases.length}
  async function createDatabase(){const name=$("#newBabyName").value.trim()||"寶寶";setBusy(true);try{const body={properties:{title:`${name}的生理紀錄`},sheets:[{properties:{title:"Records"}},{properties:{title:"SleepRecords"}},{properties:{title:"AppConfig"}}]};const created=await googleFetch("https://sheets.googleapis.com/v4/spreadsheets",{method:"POST",body:JSON.stringify(body)});const id=created.spreadsheetId,now=new Date().toISOString();await googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values:batchUpdate`,{method:"POST",body:JSON.stringify({valueInputOption:"RAW",data:[{range:"Records!A1:I1",values:[RECORD_HEADERS]},{range:"SleepRecords!A1:H1",values:[SLEEP_HEADERS]},{range:"AppConfig!A1:B4",values:[["schemaVersion","1"],["appIdentifier","baby-record-pwa"],["babyName",name],["createdAt",now]]}]})});await googleFetch(`https://www.googleapis.com/drive/v3/files/${id}?fields=id,name`,{method:"PATCH",body:JSON.stringify({appProperties:{[MARKER_KEY]:MARKER_VALUE}})});$("#createModal").hidden=true;await chooseDatabase({id,name:`${name}的生理紀錄`});showToast("資料庫建立完成") }catch(error){showError(error)}finally{setBusy(false)}}
  async function validateDatabase(id){const data=await googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent("AppConfig!A1:B4")}`);const rows=data.values||[];const config=Object.fromEntries(rows.filter(r=>r.length>1).map(r=>[r[0],r[1]]));if(config.appIdentifier!=="baby-record-pwa")throw new Error("這份試算表不是寶寶生理紀錄資料庫");return config}
  async function chooseDatabase(db){setBusy(true);const config=await validateDatabase(db.id);state.database={...db,name:db.name||`${config.babyName||"寶寶"}的生理紀錄`,babyName:config.babyName||"寶寶"};localStorage.setItem(databaseStorageKey(),db.id);setBabyName(state.database.babyName);$("#databaseTitle").textContent=state.database.name;showOnly("app");await loadAll();await flushQueue();setBusy(false)}
  function showOnly(id){["welcome","databaseSetup","app"].forEach(x=>$("#"+x).hidden=x!==id)}
  function setBabyName(name){const hour=new Date().getHours();$("#greeting").textContent=`${hour<11?"早安":hour<18?"午安":"晚安"}，${name}`;$("#profileButton").textContent=name.slice(0,1)}
  async function openPicker(){try{if(!state.token)return connectGoogle();setBusy(true);await waitFor(()=>window.gapi);await new Promise((resolve,reject)=>gapi.load("picker",{callback:resolve,onerror:reject,timeout:10000,ontimeout:()=>reject(new Error("檔案選擇器載入逾時"))}));const view=new google.picker.DocsView(google.picker.ViewId.SPREADSHEETS).setIncludeFolders(false).setSelectFolderEnabled(false);new google.picker.PickerBuilder().setAppId(APP_ID).setOAuthToken(state.token).setDeveloperKey(API_KEY).addView(view).setTitle("選擇家人分享的寶寶資料庫").setCallback(async data=>{if(data.action===google.picker.Action.PICKED){try{const doc=data.docs[0];await chooseDatabase({id:doc.id,name:doc.name})}catch(error){showError(error)}}}).build().setVisible(true)}catch(error){showError(error)}finally{setBusy(false)}}
  async function inviteFamily(){const email=$("#familyEmail").value.trim();if(!/^\S+@\S+\.\S+$/.test(email))return showToast("請輸入家人的 Gmail");setBusy(true);try{await googleFetch(`https://www.googleapis.com/drive/v3/files/${state.database.id}/permissions?sendNotificationEmail=true`,{method:"POST",body:JSON.stringify({type:"user",role:"writer",emailAddress:email})});$("#familyEmail").value="";showToast("邀請已寄出；請家人登入本網站並選擇加入資料庫") }catch(error){showError(error)}finally{setBusy(false)}}

  async function loadAll(){setConnection("syncing");const [recordData,sleepData]=await Promise.all([getValues("Records!A2:I"),getValues("SleepRecords!A2:H")]);const records=(recordData.values||[]).filter(r=>r[0]).map(r=>({id:String(r[0]),kind:String(r[1]||""),date:String(r[2]||""),time:String(r[3]||""),summary:String(r[4]||""),details:parseJSON(r[5]),readOnly:false}));let active=null;const sleepRecords=[];(sleepData.values||[]).filter(r=>r[0]).forEach(r=>{if(r[4]==="sleeping"&&r[1])active=String(r[1]);if(r[4]==="completed"&&r[1]&&r[2]){const end=new Date(r[2]),start=new Date(r[1]);sleepRecords.push({id:String(r[0]),kind:"sleep",date:localDate(end),time:clock(start),summary:`睡眠 ${Number(r[3]||0)} 分鐘`,details:{start:String(r[1]),end:String(r[2]),duration:String(r[3]||0)},readOnly:true})}});state.activeStart=active;state.records=[...records,...sleepRecords].sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`));render();setConnection("connected")}
  async function getValues(range){return googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${state.database.id}/values/${encodeURIComponent(range)}`)}
  async function appendValues(range,values){return googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${state.database.id}/values/${encodeURIComponent(range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:"POST",body:JSON.stringify({values})})}
  async function updateValues(range,values){return googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${state.database.id}/values/${encodeURIComponent(range)}?valueInputOption=RAW`,{method:"PUT",body:JSON.stringify({values})})}
  async function upsertRecord(record){const ids=await getValues("Records!A2:A");const index=(ids.values||[]).findIndex(r=>String(r[0]||"")===record.id),now=new Date().toISOString(),details=JSON.stringify(record.details||{});let created=now;if(index>=0){const old=await getValues(`Records!H${index+2}:H${index+2}`);created=old.values?.[0]?.[0]||now}const row=[record.id,record.kind,record.date,record.time,record.summary,details,state.user.emailAddress||state.user.displayName,created,now];if(index>=0)await updateValues(`Records!A${index+2}:I${index+2}`,[row]);else await appendValues("Records!A:I",[row])}
  async function deleteRecord(record){const ids=await getValues("Records!A2:A"),index=(ids.values||[]).findIndex(r=>String(r[0]||"")===record.id);if(index<0)return;await googleFetch(`https://sheets.googleapis.com/v4/spreadsheets/${state.database.id}/values/${encodeURIComponent(`Records!A${index+2}:I${index+2}`)}:clear`,{method:"POST",body:"{}"})}
  async function saveRecord(){const record={id:state.editingId||crypto.randomUUID(),kind:state.activeKind,date:$("#recordDate").value,time:$("#recordTime").value,summary:makeSummary(state.activeKind,{...state.values,note:$("#recordNote").value}),details:{...state.values,note:$("#recordNote").value},readOnly:false};$("#recordModal").hidden=true;await performOrQueue("upsert",record)}
  async function performOrQueue(action,record){setConnection("syncing");try{if(action==="upsert")await upsertRecord(record);else await deleteRecord(record);await loadAll();showToast(action==="upsert"?"已同步到 Google 試算表":"已刪除這筆紀錄")}catch(error){queueOperation({action,record,databaseId:state.database.id});if(action==="upsert")state.records=[record,...state.records.filter(r=>r.id!==record.id)];else state.records=state.records.filter(r=>r.id!==record.id);render();setConnection(state.token?"offline":"expired");showToast("已暫存在手機，恢復連線後會同步")}}
  function queueOperation(operation){const queue=JSON.parse(localStorage.getItem("baby-record.pending")||"[]");queue.push(operation);localStorage.setItem("baby-record.pending",JSON.stringify(queue))}
  async function flushQueue(){if(!state.token||!state.database)return;const queue=JSON.parse(localStorage.getItem("baby-record.pending")||"[]"),remaining=[];for(const item of queue){if(item.databaseId!==state.database.id){remaining.push(item);continue}try{if(item.action==="upsert")await upsertRecord(item.record);else await deleteRecord(item.record)}catch{remaining.push(item)}}localStorage.setItem("baby-record.pending",JSON.stringify(remaining));if(queue.length&&!remaining.length)await loadAll()}
  async function changeSleep(){if(!navigator.onLine)return showToast("睡眠計時需要網路連線");setConnection("syncing");try{if(!state.activeStart){const now=new Date().toISOString();await appendValues("SleepRecords!A:H",[[crypto.randomUUID(),now,"","","sleeping",state.user.emailAddress||"",now,now]])}else{const data=await getValues("SleepRecords!A2:H"),rows=data.values||[];let index=-1,row;for(let i=rows.length-1;i>=0;i--){if(rows[i][4]==="sleeping"){index=i;row=rows[i];break}}if(index<0)throw new Error("找不到進行中的睡眠紀錄");const end=new Date(),start=new Date(row[1]),minutes=Math.max(0,Math.floor((end-start)/60000));await updateValues(`SleepRecords!C${index+2}:H${index+2}`,[[end.toISOString(),minutes,"completed",row[5]||"",row[6]||end.toISOString(),end.toISOString()]])}await loadAll();showToast(state.activeStart?"已開始記錄睡眠":"睡眠紀錄已完成")}catch(error){showError(error)}}

  function render(){const today=localDate(new Date()),items=state.records.filter(r=>r.date===today);$("#todayLabel").textContent=new Intl.DateTimeFormat("zh-TW",{month:"long",day:"numeric"}).format(new Date());$("#recordCount").textContent=`${items.length} 筆紀錄`;$("#milkTotal").textContent=`${items.filter(r=>r.kind==="feeding").reduce((n,r)=>n+Number(r.details.breast||0)+Number(r.details.formula||0),0)} ml`;$("#peeCount").textContent=`${items.filter(r=>r.kind==="pee").length} 次`;$("#poopCount").textContent=`${items.filter(r=>r.kind==="poop").length} 次`;renderSleep();renderRecords($("#recentRecords"),items.slice(0,4));renderHistory()}
  function renderSleep(){clearInterval(sleepTimer);const sleeping=Boolean(state.activeStart);$("#sleepStatus").textContent=sleeping?"寶寶睡眠中":"目前醒著";$("#sleepHint").textContent=sleeping?`${clock(new Date(state.activeStart))} 開始入睡`:"點一下開始計時";$("#sleepButton").textContent=sleeping?"醒來":"開始睡覺";$("#sleepButton").classList.toggle("wake",sleeping);const tick=()=>$("#sleepTimer").textContent=sleeping?timer(Date.now()-new Date(state.activeStart).getTime()):"00:00:00";tick();if(sleeping)sleepTimer=setInterval(tick,1000)}
  function renderRecords(root,records){root.replaceChildren();if(!records.length){const e=document.createElement("div");e.className="empty";e.textContent="目前還沒有紀錄";root.append(e);return}records.forEach(record=>{const meta=kinds[record.kind]||{label:record.kind,icon:"•",tone:"mint"},row=document.createElement("article"),time=document.createElement("time"),icon=document.createElement("span"),main=document.createElement("button"),del=document.createElement("button");row.className="record-row";time.textContent=record.time;icon.className=`record-icon ${meta.tone}`;icon.textContent=meta.icon;main.className="record-main";const title=document.createElement("strong"),summary=document.createElement("p");title.textContent=meta.label;summary.textContent=record.summary;main.append(title,summary);if(!record.readOnly)main.onclick=()=>openRecord(record.kind,record);del.className="delete-record";del.textContent=record.readOnly?"":"×";if(!record.readOnly)del.onclick=()=>{if(confirm(`刪除「${record.summary}」？`))performOrQueue("delete",record)};row.append(time,icon,main,del);root.append(row)})}
  function renderHistory(){const list=state.records.filter(r=>state.filter==="all"||state.filter==="feeding"&&["feeding","food"].includes(r.kind)||state.filter==="elimination"&&["pee","poop"].includes(r.kind)||state.filter==="sleep"&&r.kind==="sleep"||state.filter==="health"&&["temperature","jaundice","growth"].includes(r.kind)),groups={};list.forEach(r=>(groups[r.date]??=[]).push(r));const root=$("#historyRecords");root.replaceChildren();Object.entries(groups).forEach(([date,records])=>{const section=document.createElement("section"),h=document.createElement("h3"),box=document.createElement("div");section.className="history-group";h.textContent=`${date}　${records.length} 筆`;box.className="records";renderRecords(box,records);section.append(h,box);root.append(section)});if(!list.length){const e=document.createElement("div");e.className="empty";e.textContent="這個分類目前沒有紀錄";root.append(e)}}
  function openRecord(kind,record=null){state.activeKind=kind;state.editingId=record?.id||null;state.values={...(record?.details||{})};const now=nowFields();$("#recordDate").value=record?.date||now.date;$("#recordTime").value=record?.time||now.time;$("#recordNote").value=state.values.note||"";$("#recordTitle").textContent=`${record?"編輯":"新增"}${kinds[kind].label}紀錄`;renderFields();$("#recordModal").hidden=false}
  function renderFields(){const root=$("#recordFields");root.replaceChildren();const number=(key,label,unit,placeholder)=>addField(root,key,label,unit,placeholder,"decimal"),choices=(key,label,items)=>{const box=document.createElement("fieldset"),legend=document.createElement("legend"),row=document.createElement("div");box.className="choice-field";legend.textContent=label;row.className="choice-row";items.forEach(item=>{const b=document.createElement("button");b.type="button";b.textContent=item;b.classList.toggle("selected",state.values[key]===item);b.onclick=()=>{state.values[key]=item;renderFields()};row.append(b)});box.append(legend,row);root.append(box)};const kind=state.activeKind;if(kind==="feeding"){number("breast","母奶","ml","0");number("formula","配方奶","ml","0");choices("method","餵食方式",["奶瓶","親餵"])}if(kind==="pee"){choices("color","顏色",["透明","淡黃","黃色","深黃","橘色"]);choices("amount","尿量",["微量","少量","中量","大量"])}if(kind==="poop"){choices("shape","型態",["水狀","稀便","糊狀","軟便","顆粒"]);choices("color","顏色",["黑色","墨綠","褐色","綠色","黃色"]);choices("amount","份量",["微量","少量","中量","大量"])}if(kind==="sleep")number("duration","睡了多久","分鐘","例如 80");if(kind==="temperature")number("temperature","寶寶體溫","°C","例如 36.8");if(kind==="jaundice")number("jaundice","黃疸數值","mg/dL","請輸入數值");if(kind==="growth"){number("weight","體重","kg","例如 3.8");number("height","身長","cm","例如 52")}if(kind==="food"){addField(root,"foodName","食品名稱","","例如 十倍粥");number("foodAmount","食用份量","g","例如 30")}}
  function addField(root,key,label,unit,placeholder,inputMode="text"){const l=document.createElement("label"),wrap=document.createElement("div"),input=document.createElement("input"),b=document.createElement("b"),span=document.createElement("span");l.className="big-field";span.textContent=label;input.placeholder=placeholder;input.inputMode=inputMode;input.value=state.values[key]||"";input.oninput=()=>state.values[key]=input.value;b.textContent=unit;wrap.append(input,b);l.append(span,wrap);root.append(l)}
  function makeSummary(kind,v){if(kind==="feeding")return[v.breast&&`母奶 ${v.breast} ml`,v.formula&&`配方奶 ${v.formula} ml`].filter(Boolean).join("・")||"已記錄喝奶";if(kind==="pee")return`${v.color||"未選顏色"}・${v.amount||"未選量"}`;if(kind==="poop")return[v.shape,v.color,v.amount].filter(Boolean).join("・")||"已記錄大便";if(kind==="sleep")return`睡眠 ${v.duration||0} 分鐘`;if(kind==="temperature")return`體溫 ${v.temperature||"—"} °C`;if(kind==="jaundice")return`黃疸 ${v.jaundice||"—"} mg/dL`;if(kind==="growth")return[v.weight&&`${v.weight} kg`,v.height&&`${v.height} cm`].filter(Boolean).join("・")||"已記錄成長";return`${v.foodName||"副食品"}${v.foodAmount?` ${v.foodAmount} g`:""}`}
  function setConnection(mode){const bar=document.querySelector(".connection");bar.className=`connection ${mode==="syncing"?"syncing":mode==="connected"?"":"offline"}`;$("#connectionText").textContent=mode==="syncing"?"正在同步資料":mode==="connected"?"Google Sheets 已同步":mode==="expired"?"Google 連線已到期":"目前離線・稍後自動同步";$("#reconnect").hidden=mode!=="expired"}
  function setBusy(value){state.busy=value;$("#busy").hidden=!value}
  function showError(error){setBusy(false);showToast(error?.message||String(error))}
  function showToast(message){clearTimeout(toastTimer);$("#toast").textContent=message;$("#toast").classList.add("show");toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),3600)}
  function parseJSON(value){try{return JSON.parse(value||"{}")}catch{return{}}}
  function pad(n){return String(n).padStart(2,"0")}
  function localDate(d){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
  function clock(d){return`${pad(d.getHours())}:${pad(d.getMinutes())}`}
  function nowFields(){const d=new Date();return{date:localDate(d),time:clock(d)}}
  function timer(ms){const s=Math.max(0,Math.floor(ms/1000));return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(pad).join(":")}
  function showTab(name){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("#"+name+"Screen").classList.add("active");document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));scrollTo(0,0)}
  function signOut(){if(state.token)google.accounts.oauth2.revoke(state.token,()=>{});state.token=null;state.user=null;state.database=null;showOnly("welcome")}

  Object.entries(kinds).forEach(([kind,meta])=>{const b=document.createElement("button");b.className="action-card";const icon=document.createElement("span"),title=document.createElement("strong"),small=document.createElement("small");icon.className=meta.tone;icon.textContent=meta.icon;title.textContent=meta.label;small.textContent="新增紀錄";b.append(icon,title,small);b.onclick=()=>openRecord(kind);$("#actionGrid").append(b)});
  [["all","全部"],["feeding","餵食"],["elimination","排泄"],["sleep","睡眠"],["health","健康"]].forEach(([value,label])=>{const b=document.createElement("button");b.textContent=label;b.classList.toggle("active",value==="all");b.onclick=()=>{state.filter=value;document.querySelectorAll("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderHistory()};$("#filters").append(b)});
  $("#googleLogin").onclick=connectGoogle;$("#reconnect").onclick=async()=>{await connectGoogle()};$("#setupSignOut").onclick=signOut;$("#createChoice").onclick=()=>$("#createModal").hidden=false;$("#joinChoice").onclick=openPicker;$("#createDatabase").onclick=createDatabase;$("#inviteFamily").onclick=inviteFamily;$("#sleepButton").onclick=changeSleep;$("#saveRecord").onclick=saveRecord;$("#saveRecordTop").onclick=saveRecord;$("#quickAdd").onclick=()=>openRecord("feeding");$("#showAll").onclick=()=>showTab("history");$("#profileButton").onclick=()=>showTab("settings");$("#openSheet").onclick=()=>window.open(`https://docs.google.com/spreadsheets/d/${state.database.id}/edit`,"_blank");$("#switchDatabase").onclick=async()=>{await loadDatabaseChoices();showOnly("databaseSetup")};$("#signOut").onclick=signOut;document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).hidden=true);window.addEventListener("online",async()=>{if(state.token&&state.database){try{await flushQueue();await loadAll()}catch{}}});if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));prepareGoogle().catch(()=>{});showOnly("welcome");
})();
